'use client';
import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { api, money } from '@/lib/api';

type Summary = { received_paise:number;allocated_paise:number;pending_paise:number;disbursed_paise:number;failed_paise:number;remaining_paise:number;last_indexed_at:string };
type District = { district_code:string;scheme_name:string;source_type:string;beneficiary_count:number;disbursed_paise:number;pending_paise:number };
export default function Home() {
  const [summary,setSummary]=useState<Summary>(); const [districts,setDistricts]=useState<District[]>([]); const [reference,setReference]=useState(''); const [proof,setProof]=useState<any>(); const [error,setError]=useState('');
  useEffect(()=>{api<Summary>('/public/summary').then(setSummary).catch(()=>{});api<District[]>('/public/districts').then(setDistricts).catch(()=>{});},[]);
  async function verify(e:FormEvent){e.preventDefault();setError('');try{const p=await api<any>(`/public/proof/${encodeURIComponent(reference)}`);if(p.found===false)throw new Error('No public proof found');setProof(p)}catch(e){setProof(null);setError(e instanceof Error?e.message:'Not found')}}
  const max=Math.max(...districts.map(d=>d.disbursed_paise),1);
  return <main className="shell">
    <nav className="nav"><div className="brand"><span className="brandmark">R</span> ReliefChain</div><div className="navlinks"><a href="#flow">How it works</a><a href="#districts">Districts</a><a href="#verify">Verify</a><Link className="button" href="/login">Institution login</Link></div></nav>
    <section className="hero"><div><span className="eyebrow"><i className="dot"/> Live Assam flood response</span><h1>Every rupee.<br/>Visible. Verifiable.</h1><p>Follow relief money from government and NGO funds to affected families through a tamper-evident ledger—without exposing anyone’s personal identity.</p><div className="hero-actions"><a className="button" href="#districts">Explore fund flow</a><a className="button secondary" href="#verify">Verify a payment</a></div></div>
      <aside className="trust-card"><div className="trust-head"><div><b>Ledger assurance</b><span style={{display:'block',color:'var(--muted)',fontSize:12,marginTop:4}}>Hyperledger Fabric network</span></div><span className="seal">✓</span></div>{[['01','Government fund registered'],['02','District allocation approved'],['03','Beneficiary payout settled']].map(([n,t])=><div className="chain-row" key={n}><div className="chain-icon">{n}</div><div><strong>{t}</strong><span>Cryptographically signed • immutable event</span></div></div>)}</aside>
    </section>
    <section className="section"><div className="section-title"><div><h2>Relief at a glance</h2><p>Indexed from confirmed ledger events</p></div><span className="eyebrow"><i className="dot"/> {summary?'Synchronized':'Connecting'}</span></div><div className="metrics">
      {[['Funds received',summary?.received_paise],['Funds allocated',summary?.allocated_paise],['Families paid',summary?.disbursed_paise],['Available balance',summary?.remaining_paise]].map(([label,value],i)=><div className="card metric" key={String(label)}><div className="metric-label">{label}</div><div className="metric-value">{money(value as number)}</div><div className="metric-foot">{i===2?`${money(summary?.pending_paise)} pending`:'Fabric-indexed total'}</div></div>)}</div>
    </section>
    <section className="section" id="flow"><div className="section-title"><div><h2>One continuous chain of trust</h2><p>Ownership and balances are checked at every handoff.</p></div></div><div className="card flow">{[['1','Fund source','Government / NGO'],['2','Allocation','District + scheme'],['3','Settlement','Simulated bank rail'],['4','Verification','Family + auditor']].map(x=><div className="flow-step" key={x[0]}><div className="flow-node">{x[0]}</div><b>{x[1]}</b><small>{x[2]}</small></div>)}</div></section>
    <section className="section grid2" id="districts"><div className="card panel"><h3>District distribution</h3>{districts.length?districts.map(d=><div className="district" key={`${d.district_code}-${d.scheme_name}`}><div className="district-top"><span><b>{d.district_code}</b> · {d.scheme_name}</span><span>{money(d.disbursed_paise)}</span></div><div className="bar"><span style={{width:`${Math.max(6,d.disbursed_paise/max*100)}%`}}/></div></div>):<p className="muted">Aggregate groups appear after at least three beneficiaries, protecting small cohorts.</p>}</div>
      <div className="card panel verify" id="verify"><h3>Verify a disbursement</h3><p>Enter the public reference from a beneficiary receipt. Personal identity is never shown.</p><form onSubmit={verify}><input value={reference} onChange={e=>setReference(e.target.value)} placeholder="RC-2026-XXXXXXXX"/><button className="button" type="submit">Check ledger proof</button></form>{error&&<div className="error">{error}</div>}{proof&&<div className="proof"><span className={`status ${proof.status}`}>{proof.status}</span><p>{money(proof.amount_paise)} · {proof.district_code}<br/>{proof.scheme_name}</p><b>Transaction</b><br/>{proof.proof.transactionId}<br/><br/><b>Committed</b><br/>{new Date(proof.proof.committedAt).toLocaleString()}</div>}</div>
    </section><footer className="footer"><span>ReliefChain · Hackathon MVP · Synthetic data only</span><span>No Aadhaar, phone, or bank details are stored on-chain.</span></footer>
  </main>
}
