'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { api, money } from '@/lib/api';

type Context={disasters:any[];schemes:any[];sources:any[];allocations:any[];beneficiaries:any[];disbursements:any[]};
export default function Operator(){
  const router=useRouter();const[data,setData]=useState<Context>();const[kind,setKind]=useState('payout');const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);
  const load=()=>api<Context>('/operator/context').then(setData).catch(()=>router.push('/login'));useEffect(()=>{void load()},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const form=new FormData(e.currentTarget);const rupees=Number(form.get('amount'));let path='';let body:any={};
    if(kind==='source'){path='/operator/fund-sources';body={disasterId:form.get('disasterId'),name:form.get('name'),sourceType:form.get('sourceType'),amountPaise:rupees*100}}
    if(kind==='allocation'){path='/operator/allocations';body={sourceId:form.get('sourceId'),schemeId:form.get('schemeId'),districtCode:form.get('districtCode'),amountPaise:rupees*100}}
    if(kind==='beneficiary'){path='/operator/beneficiaries';body={name:form.get('name'),aadhaar:form.get('aadhaar'),phone:form.get('phone'),schemeId:form.get('schemeId'),districtCode:form.get('districtCode'),promisedPaise:rupees*100}}
    if(kind==='payout'){path='/operator/disbursements';body={allocationId:form.get('allocationId'),beneficiaryId:form.get('beneficiaryId'),amountPaise:rupees*100,idempotencyKey:`portal-${crypto.randomUUID()}`,simulatedOutcome:form.get('outcome')}}
    try{await api(path,{method:'POST',body:JSON.stringify(body)});setMessage('Transaction submitted and ledger proof created.');(e.target as HTMLFormElement).reset();await load()}catch(e){setMessage(e instanceof Error?e.message:'Transaction failed')}finally{setBusy(false)}}
  const user=typeof window==='undefined'?null:JSON.parse(localStorage.getItem('reliefchain-user')||'null');
  function logout(){localStorage.clear();router.push('/login')}
  return <main className="portal"><aside className="sidebar"><div className="brand"><span className="brandmark">R</span> ReliefChain</div><div style={{marginTop:42}}><button className="side-link active">Overview</button><a className="side-link" href="/">Public dashboard</a><button className="side-link" onClick={logout}>Sign out</button></div></aside><section className="portal-main"><header className="portal-top"><div><p className="eyebrow"><i className="dot"/> Operator console</p><h1>Fund operations</h1></div><div style={{textAlign:'right'}}><b>{user?.displayName}</b><div className="muted" style={{fontSize:12}}>{user?.organization}</div></div></header>
    <div className="metrics" style={{marginBottom:20}}>{[['Fund sources',data?.sources.length],['Allocations',data?.allocations.length],['Beneficiaries',data?.beneficiaries.length],['Disbursements',data?.disbursements.length]].map(([l,v])=><div className="card metric" key={String(l)}><div className="metric-label">{l}</div><div className="metric-value">{v??'—'}</div></div>)}</div>
    <div className="grid2"><div className="card panel"><h3>Create a verified transaction</h3><div className="tabs">{[['payout','Payout'],['source','Fund'],['allocation','Allocation'],['beneficiary','Beneficiary']].map(([id,label])=><button key={id} onClick={()=>setKind(id)} className={`button ${kind===id?'':'secondary'}`}>{label}</button>)}</div>
      <form onSubmit={submit} className="form-grid">
        {kind==='source'&&<><div className="field wide"><label>Fund name</label><input name="name" required placeholder="Relief fund name"/></div><div className="field"><label>Disaster</label><select name="disasterId">{data?.disasters.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div><div className="field"><label>Source type</label><select name="sourceType"><option value="STATE_GOVERNMENT">State government</option><option value="CENTRAL_GOVERNMENT">Central government</option><option value="NGO">NGO</option></select></div></>}
        {kind==='allocation'&&<><div className="field"><label>Fund source</label><select name="sourceId">{data?.sources.map(x=><option value={x.id} key={x.id}>{x.name} · {money(x.amount_paise-x.allocated_paise)}</option>)}</select></div><div className="field"><label>Scheme</label><select name="schemeId">{data?.schemes.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div><div className="field"><label>District code</label><input name="districtCode" defaultValue="AS-KAM" required/></div></>}
        {kind==='beneficiary'&&<><div className="field"><label>Synthetic name</label><input name="name" required/></div><div className="field"><label>Synthetic Aadhaar</label><input name="aadhaar" pattern="[0-9]{12}" required/></div><div className="field"><label>Registered phone</label><input name="phone" defaultValue="+91" pattern="\+91[0-9]{10}" required/></div><div className="field"><label>District code</label><input name="districtCode" defaultValue="AS-KAM" required/></div><div className="field wide"><label>Scheme</label><select name="schemeId">{data?.schemes.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div></>}
        {kind==='payout'&&<><div className="field wide"><label>Allocation</label><select name="allocationId">{data?.allocations.map(x=><option value={x.id} key={x.id}>{x.district_code} · {money(x.amount_paise-x.reserved_paise-x.disbursed_paise)} available</option>)}</select></div><div className="field wide"><label>Beneficiary commitment</label><select name="beneficiaryId">{data?.beneficiaries.map(x=><option value={x.id} key={x.id}>{x.district_code} · {x.beneficiary_ref.slice(0,18)}…</option>)}</select></div><div className="field"><label>Simulated outcome</label><select name="outcome"><option value="SETTLED">Success</option><option value="FAILED">Failure</option></select></div></>}
        <div className="field"><label>{kind==='beneficiary'?'Promised amount':'Amount'} (₹)</label><input name="amount" type="number" min="1" required/></div><div className="wide">{message&&<p className={message.includes('submitted')?'metric-foot':'error'}>{message}</p>}<button className="button" disabled={busy}>{busy?'Submitting…':'Submit to ledger'}</button></div>
      </form></div>
      <div className="card panel"><h3>Latest disbursements</h3><div className="table-card"><table className="table"><thead><tr><th>Reference</th><th>Amount</th><th>Status</th></tr></thead><tbody>{data?.disbursements.slice(0,8).map(x=><tr key={x.id}><td>{x.public_reference}</td><td>{money(x.amount_paise)}</td><td><span className={`status ${x.status}`}>{x.status}</span></td></tr>)}</tbody></table></div></div>
    </div></section></main>
}
