#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NET="$ROOT/fabric/network"
npm run build -w @reliefchain/chaincode
rm -f "$NET/relief-funds.tgz"
docker run --rm -v "$ROOT:/workspace" -w /workspace --network reliefchain_fabric hyperledger/fabric-tools:2.5.12 peer lifecycle chaincode package /workspace/fabric/network/relief-funds.tgz --path /workspace/fabric/chaincode --lang node --label relief-funds_1
for org in government ngo auditor; do
  case "$org" in government) msp=GovernmentMSP; port=7051;; ngo) msp=NgoMSP; port=9051;; auditor) msp=AuditorMSP; port=11051;; esac
  docker run --rm --network reliefchain_fabric -v "$ROOT:/workspace" -e CORE_PEER_TLS_ENABLED=true -e CORE_PEER_LOCALMSPID="$msp" -e CORE_PEER_ADDRESS="peer0.$org.example.com:$port" -e CORE_PEER_MSPCONFIGPATH="/workspace/fabric/network/organizations/peerOrganizations/$org.example.com/users/Admin@$org.example.com/msp" -e CORE_PEER_TLS_ROOTCERT_FILE="/workspace/fabric/network/organizations/peerOrganizations/$org.example.com/peers/peer0.$org.example.com/tls/ca.crt" hyperledger/fabric-tools:2.5.12 peer lifecycle chaincode install /workspace/fabric/network/relief-funds.tgz
done
PACKAGE_ID=$(docker run --rm --network reliefchain_fabric -v "$ROOT:/workspace" -e CORE_PEER_LOCALMSPID=GovernmentMSP -e CORE_PEER_ADDRESS=peer0.government.example.com:7051 -e CORE_PEER_MSPCONFIGPATH=/workspace/fabric/network/organizations/peerOrganizations/government.example.com/users/Admin@government.example.com/msp -e CORE_PEER_TLS_ENABLED=true -e CORE_PEER_TLS_ROOTCERT_FILE=/workspace/fabric/network/organizations/peerOrganizations/government.example.com/peers/peer0.government.example.com/tls/ca.crt hyperledger/fabric-tools:2.5.12 peer lifecycle chaincode queryinstalled | sed -n 's/^Package ID: \([^,]*\),.*/\1/p')
for org in government ngo auditor; do
  case "$org" in government) msp=GovernmentMSP; port=7051;; ngo) msp=NgoMSP; port=9051;; auditor) msp=AuditorMSP; port=11051;; esac
  docker run --rm --network reliefchain_fabric -v "$ROOT:/workspace" -e CORE_PEER_TLS_ENABLED=true -e CORE_PEER_LOCALMSPID="$msp" -e CORE_PEER_ADDRESS="peer0.$org.example.com:$port" -e CORE_PEER_MSPCONFIGPATH="/workspace/fabric/network/organizations/peerOrganizations/$org.example.com/users/Admin@$org.example.com/msp" -e CORE_PEER_TLS_ROOTCERT_FILE="/workspace/fabric/network/organizations/peerOrganizations/$org.example.com/peers/peer0.$org.example.com/tls/ca.crt" hyperledger/fabric-tools:2.5.12 peer lifecycle chaincode approveformyorg -o orderer.example.com:7050 --ordererTLSHostnameOverride orderer.example.com --tls --cafile /workspace/fabric/network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt --channelID reliefchannel --name relief-funds --version 1.0 --package-id "$PACKAGE_ID" --sequence 1
done
docker run --rm --network reliefchain_fabric -v "$ROOT:/workspace" -e CORE_PEER_TLS_ENABLED=true -e CORE_PEER_LOCALMSPID=GovernmentMSP -e CORE_PEER_ADDRESS=peer0.government.example.com:7051 -e CORE_PEER_MSPCONFIGPATH=/workspace/fabric/network/organizations/peerOrganizations/government.example.com/users/Admin@government.example.com/msp -e CORE_PEER_TLS_ROOTCERT_FILE=/workspace/fabric/network/organizations/peerOrganizations/government.example.com/peers/peer0.government.example.com/tls/ca.crt hyperledger/fabric-tools:2.5.12 peer lifecycle chaincode commit -o orderer.example.com:7050 --ordererTLSHostnameOverride orderer.example.com --tls --cafile /workspace/fabric/network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt --channelID reliefchannel --name relief-funds --version 1.0 --sequence 1 --peerAddresses peer0.government.example.com:7051 --tlsRootCertFiles /workspace/fabric/network/organizations/peerOrganizations/government.example.com/peers/peer0.government.example.com/tls/ca.crt --peerAddresses peer0.ngo.example.com:9051 --tlsRootCertFiles /workspace/fabric/network/organizations/peerOrganizations/ngo.example.com/peers/peer0.ngo.example.com/tls/ca.crt --peerAddresses peer0.auditor.example.com:11051 --tlsRootCertFiles /workspace/fabric/network/organizations/peerOrganizations/auditor.example.com/peers/peer0.auditor.example.com/tls/ca.crt
echo "relief-funds chaincode deployed"
